---
# Enable sudo. Required for Docker. For details, see the following link
# https://docs.travis-ci.com/user/docker/
sudo: "required"

# Use a specific composer home, as composer will not show which home it's
# currently using and this build script is operating in multiple environments.
env:
  COMPOSER_HOME: "/tmp/composer"

language: "php"
php:
  - "7.0"

services:
  - "docker"

before_install:
  - 'docker login --username "${CI_DOCKER_USERNAME}" --password="${CI_DOCKER_PASSWORD}" quay.io'
  - "mkdir -p ${COMPOSER_HOME}"
  - "sudo build/ci/install-git-crypt.sh"
  - 'printf "%s" ${CI_BASE64_GPG_PRIVATE_KEY} | base64 -d | gpg --import'
  - "make vcs-auth-setup"
  - "make compose-up"

install:
  - "make app-dependencies app-install"

script:
  - "true"

deploy:
  - provider: "script"
    # Normally, travis will attempt to stash all files before it compiles and deploys container
    skip_cleanup: true
    script: "NAME=magento make container-build container-push"
    "on":
      tags: true
