---
# Enable sudo. Required for Docker. For details, see the following link
# https://docs.travis-ci.com/user/docker/
sudo: "required"

language: "php"
php:
  - "7.0"

services:
  - "docker"

before_install:
  - "make compose-up"

install:
  - "make app-dependencies app-install app-static"

deploy:
  - provider: "script"
    script: "NAME=magento make container-build container-push"
    "on":
      tags: true
