---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}"
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        heritage: {{ .Release.Service | quote }}
        release: {{ .Release.Name | quote }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      # The installer should have created a service account for the job that allows the job to create secrets, based
      # on the result of the install process.
      serviceAccountName: "magento-installer"
      # There's a race condition in which, if the database is not ready by the time the job runs, the job will just
      # timeout. In that case, we should just restart it.
      restartPolicy: "OnFailure"
      volumes:
        - name: "magento-pv"
          persistentVolumeClaim:
            claimName: {{ template "magento.fullname" . }}
      containers:
        - name: "install-magento"
          volumeMounts:
            - name: "magento-pv"
              mountPath: "/var/www/pub/media"
              subPath: "media"
          env:
            - name: "DATABASE_HOST"
              value: {{ template "mysql.fullname" . }}
            - name: "DATABASE_NAME"
              value: {{ default "magento" .Values.mysql.mysqlDatabase | quote }}
            - name: "DATABASE_USER"
              value: {{ .Values.mysql.mysqlUser | quote }}
            - name: "ADMIN_USER"
              value: {{ default "admin" .Values.magento.admin.user }}
            - name: "ADMIN_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: {{ template "magento.fullname" . }}
                  key: "adminPassword"
            - name: "BASE_URL"
              value: {{ required "You need to specify a base URL" .Values.magento.baseUrl }}
            - name: "DATABASE_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: {{ template "mysql.fullname" . }}
                  key: "mysql-password"
            - name: "REDIS_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: {{ template "redis.fullname" . }}
                  key: "redis-password"
            - name: "NAMESPACE"
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: "HELM_RELEASE"
              value: {{ .Release.Name | quote }}
          image: {{ .Values.pod.magento.image | quote }}
          command:
            - "su"
            - "--shell=/bin/bash"
            - "www-data"
            - "/opt/m2onk8s/bin/install.sh"
      securityContext:
        fsGroup: 33
        supplementalGroups:
          - 33
