---
apiVersion: "v1"
kind: "Secret"
metadata:
  labels:
    app: {{ template "magento.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "magento.fullname" . }}
data:
{{ if .Values.magento.admin.password }}
    adminPassword: {{ .Values.admin.password | b64enc | quote }}
{{ else }}
    adminPassword: {{ randAlphaNum 10 | b64enc | quote }}
{{ end -}}
