---
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  name: "__SERVICE_ACCOUNT_NAME__"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app: {{ template "__CHART__.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
